### ISSUE TITLE
Rendering

### ISSUE THREAD

**Issue by thowell** [kevinzakka/mujoco_cube#1]
With recent versions of MuJoCo I see weird rendering: 

<img width="1264" alt="image" src="https://github.com/kevinzakka/mujoco_cube/assets/12521315/42ef69da-5116-48af-93b5-64c034252b0b">

Do you have an idea of why this might be happening?

**Comment by kevinzakka** [comment]
Hi @thowell, can you temporarily apply the fix [here](https://github.com/google-deepmind/mujoco/commit/f0608648cbc17bcb6f0387dcbb0d550a9c7a2882)? This is a super weird MuJoCo compiler issue but Alessio fixed the model in the MuJoCo repository. If it works for you, we can update the code here!

**Comment by kevinzakka** [comment]
@thowell Made a [PR](#2), let me know if it fixes your problem!

**Comment by thowell** [comment]
Thanks Kevin!

**Comment by kevinzakka** [comment]
Thank you for the bug report @thowell!
