### ISSUE TITLE
Potential rubik's cube URDF format

### ISSUE THREAD

**Issue by cypypccpy** [kevinzakka/mujoco_cube#3]
Hi @kevinzakka ,

Great job! I would like to ask if you have tried the URDF version of rubik's cube? Or do you think we can implement a cube with the same functions as your repo in URDF format?

Many thanks.

**Comment by kevinzakka** [comment]
Hi @cypypccpy, I don't really work with URDFs but I believe @RussTedrake has [a version](https://github.com/RussTedrake/manipulation/blob/bb9d3844da27f48ce4ede39b6bacb4d216829a22/book/robot/rubiks_cube.ipynb#L79) that works in Drake, albeit it might have Drake-specific directives that might not work in other simulators.

**Comment by RussTedrake** [comment]
I generated it programmatically for sdf, not urdf, but it doesn't have any drake-specific directives: https://github.com/RussTedrake/manipulation/blob/bb9d3844da27f48ce4ede39b6bacb4d216829a22/manipulation/models/rubiks_cube.sdf

**Comment by cypypccpy** [comment]
Thanks @kevinzakka and @RussTedrake !

I feel like I can refer to [https://github.com/RussTedrake/manipulation/blob/bb9d3844da27f48ce4ede39b6bacb4d216829a22/manipulation/models/rubiks_cube.sdf](https://github.com/RussTedrake/manipulation/blob/bb9d3844da27f48ce4ede39b6bacb4d216829a22/manipulation/models/rubiks_cube.sdf) to generate a URDF format of rubik's cube.

Very helpful!

**Comment by supersglzc** [comment]
Hi I would like to followup on this issue. Have you succeed on generating the URDF format of the cube @cypypccpy ?

Thanks!
