### ISSUE TITLE
Instability after many steps

### ISSUE THREAD

**Issue by jjyyxx** [kevinzakka/mujoco_cube#4]
The model becomes instable after many steps, even with simplest control. Repro as follows. Could you investigate the cause? Or suggest workarounds to make the model more robust?

```python
import os
os.environ["MUJOCO_GL"] = "egl"
import mujoco
assert mujoco.__version__ == '3.2.3'

model = mujoco.MjModel.from_xml_path("cube_3x3x3.xml")
data = mujoco.MjData(model)
data.ctrl[0] = 0.0195

renderer = mujoco.Renderer(model, height=240, width=320)

mujoco.mj_step(model, data, nstep=20845)
renderer.update_scene(data)
normal = renderer.render()

mujoco.mj_step(model, data, nstep=1)
renderer.update_scene(data)
abnormal = renderer.render()

from PIL import Image
Image.fromarray(normal).save("normal.png")
Image.fromarray(abnormal).save("abnormal.png")
```
![normal](https://github.com/user-attachments/assets/5b487966-060d-475b-bd68-ea23f3994861)
Normal

![abnormal](https://github.com/user-attachments/assets/a4b247c1-2d03-4b9b-9b11-96df086397db)
Abnormal

**Comment by kevinzakka** [comment]
The timestep is really high right now. Just lower it until the instabilities go away, but not too much or it will be too slow.

**Comment by kevinzakka** [comment]
Hi @jjyyxx, did lowering the timestep help?
